### PR TITLE
Added basic pattern matching to some code

### PR DESCRIPTION
**Pull request by thyrgle**
Although there is definitely more refactoring to be done after this, I have implemented some pattern matching for the code largely based off of [this article.](https://kerflyn.wordpress.com/2012/05/09/towards-pattern-matching-in-java/)

I use it for now to check if an object is true, although much more can be written using the pattern matching "paradigm" (right word to use? idk. Hopefully you get the point...)

### CODE REVIEW

**Comment by thyrgle** [comment]
Interesting, the code runs on my machine...

**Comment by thyrgle** [comment]
Oh, I forgot about the WebIDE which uses regex.Pattern, which doesn't implement Pattern, fixed by making the name MyPattern, possible a better name should be used.

**Comment by phase** [comment]
Looks great, but I'm (really @kirbyfan64) transitioning the project to C because it's faster overall, so the Java interpreter will be left alone on the `java-interpreter` branch. We're mostly working to get the C implementation up to par with the Java one, then we'll start adding new features again and maybe (probs not) update the Java implementation.

**Comment by thyrgle** [comment]
It doesn't sound like you're going to get rid of it, and you probably know this, but just in case: I wouldn't get rid of the Java implementation as there are often Java implementations of languages that are written in C such as CPython vs Jython.

**Comment by phase** [comment]
@thyrgle Instead of updating the Java-impl, we'll be using JNI bindings for a Java library to parse the code through Java, which is how the WebIDE will still be written in it.

**Pull request merged**
