### PR TITLE
Add C implementation

### PR DESCRIPTION
**Pull request by kirbyfan64**
Please try not to freak out when you see the code... ;)

### CODE REVIEW

**Comment by phase** [comment]
Wow.... Wasn't expecting that...

Do you want to build using fbuild or use a Makefile?

**Comment by kirbyfan64** [comment]
@phase It should be buildable using a Makefile, but I use Fbuild...because.

I tried to comment it...

**Comment by phase** [comment]
@kirbyfan64 We're also going to have to figure out how to call it in Java, along with keeping the Maven project for the WebIDE. What are the methods declarations for parsing in your C code? 

I'm looking for something like `public String parse(String s)`, as that is what is in the java code. (The String that is returned is anything that should be outputted to the string, like `12+o` would return `"3"`, while `12` wouldn't return anything, but the objects would be pushed to the stack.)

**Comment by kirbyfan64** [comment]
@phase You'd want to call `excs(the_string,1)`. Unfortunately, I didn't add string returns yet. It's really easy, but I wanted to add more of O's features first.

**Comment by phase** [comment]
Do you want to make another file for using the Java API?

Something with:
```
#include <jni.h>
#include "WebIDE.h"
JNIEXPORT jstring JNICALL Java_WebIDE_parse(JNIEnv *env, jobject obj, jstring){
    //...
}
```

**Comment by phase** [comment]
Lookin good! I'll make a wrapper file for the Java stuff.

**Comment by kirbyfan64** [comment]
@phase I can make the wrapper! I already have some code down.

**Comment by phase** [comment]
@kirbyfan64 Good, cause I haven't looked at it :hurtrealbad:

**Comment by phase** [comment]
@kirbyfan64 Are you working on anything right now? I don't want to make a bunch of commits and find out you had been doing the same.

**Comment by kirbyfan64** [comment]
@phase JNI stuff and some more ops (`e`, `(`, `)`, `r`, `` ` ``). Progress slowed down a bit due to schoolwork...but it's progress!! :)

**Comment by kirbyfan64** [comment]
@phase So...for implementing `%` for strings, is there a particular regex library you would like me to use? I was thinking of Plan 9's [libregexp UNIX port](https://github.com/0intro/libregexp), since it's really light and has a nice API, or maybe PCRE?

**Comment by phase** [comment]
Looks good to me!

**Comment by phase** [comment]
@kirbyfan64 Shouldn't the `excs` return a string?

**Comment by kirbyfan64** [comment]
@phase `excs` is only for the command-line interface. The Java bindings will call `exc` directly.

**Comment by phase** [comment]
But what about portability? I was trying to port it to my 3ds, when I found that I had use  exc and supply a stack, when excs inky requires a string.

**Comment by kirbyfan64** [comment]
@phase Well, it's kind of ugly, but you can just do:

```c
excs("",0); // init the stacks
exc(the_character,rst); // run something
excs("",1); // clean up
```

3DS? I was starting to think I was the only person around who had one! :)

**Comment by phase** [comment]
img
:cat: 

How would I get the root stack if I'm in a different file? I think making excs return a string would be the easiest thing to do.

**Comment by kirbyfan64** [comment]
@phase That just takes a lot of re-alloc-ing...maybe you're right. :/ Ultimately, the root stack doesn't make a difference; I'll need to export it to Java probably anyway.

How the hell did you mod the 3DS? That looks awesome...

**Comment by phase** [comment]
https://smealum.github.io/3ds I used Tubehax to install oot3dhax, which I use now. YouTube is the only app still available that you can install Homebrew through.

**Comment by phase** [comment]
I've protected the Java branch, so development of O has completely switched over to C!

**Comment by phase** [comment]
I say let's get Travis set up and merge!

**Comment by kirbyfan64** [comment]
@phase Could you try it out a bit first? After all, you created O, so you can probably find things I missed. Right now, the only major things missing are regexes and code blocks.

Also, just let me know if there's anything in the code you don't understand (because I didn't comment it well enough or something)! :)

**Comment by kirbyfan64** [comment]
@phase Uhhh...I didn't do code blocks yet...

**Comment by phase** [comment]
@kirbyfan64 I merged it so you can just push to the repo directly instead of maintaining a fork.

As for code blocks, I think we should do variables first. The code blocks are just strings that are run as code, so they shouldn't be too difficult. I also think making it less APL-like, as it may look complicated to people (and me!).

**Comment by phase** [comment]
Let's also move this convo to #16

**Pull request merged**
